# Generated by Django 4.2.11 on 2024-08-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0003_class_student_alter_class_category_alter_class_price_and_more'),
        ('cupon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('class1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class_app.class')),
                ('cupon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupon', to='cupon_app.cupon')),
            ],
        ),
    ]
