# Generated by Django 4.2.11 on 2024-08-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_app', '0001_initial'),
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_name', to='teacher_app.teacher'),
        ),
    ]
