# Generated by Django 4.2.11 on 2024-08-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
        ('category_app', '0002_category_clas_alter_category_name'),
        ('teacher_app', '0002_remove_teacher_clas_alter_teacher_category_and_more'),
        ('class_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(related_name='student', to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='category_app.category'),
        ),
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher_name', to='teacher_app.teacher'),
        ),
    ]
