# Generated by Django 4.2.11 on 2024-08-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('rate', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class', to='class_app.class')),
            ],
        ),
    ]
