# Generated by Django 4.2.11 on 2024-08-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='clas',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.FloatField(),
        ),
    ]
