# Generated by Django 4.2.11 on 2024-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_class_student_alter_class_category_alter_class_price_and_more'),
        ('category_app', '0002_category_clas_alter_category_name'),
        ('teacher_app', '0002_remove_teacher_clas_alter_teacher_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='clas',
            field=models.ManyToManyField(null=True, related_name='clas', to='class_app.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='000000000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='category',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.ManyToManyField(null=True, related_name='category', to='category_app.category'),
        ),
    ]
