# Generated by Django 4.2.11 on 2024-08-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_class_student_alter_class_category_alter_class_price_and_more'),
        ('cupon_app', '0001_initial'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ManyToManyField(null=True, related_name='clss', to='class_app.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupn', to='cupon_app.cupon'),
        ),
        migrations.AddField(
            model_name='student',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='000000000000000', max_length=15),
        ),
    ]
