# Generated by Django 4.2.11 on 2024-08-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_initial'),
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cls', to='class_app.class'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
